###################################################################

# Created by write_sdc on Fri Dec 29 00:55:26 2023

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
set_load -pin_load 10 [get_ports rst]
set_load -pin_load 10 [get_ports {a_reg[31]}]
set_load -pin_load 10 [get_ports {a_reg[30]}]
set_load -pin_load 10 [get_ports {a_reg[29]}]
set_load -pin_load 10 [get_ports {a_reg[28]}]
set_load -pin_load 10 [get_ports {a_reg[27]}]
set_load -pin_load 10 [get_ports {a_reg[26]}]
set_load -pin_load 10 [get_ports {a_reg[25]}]
set_load -pin_load 10 [get_ports {a_reg[24]}]
set_load -pin_load 10 [get_ports {a_reg[23]}]
set_load -pin_load 10 [get_ports {a_reg[22]}]
set_load -pin_load 10 [get_ports {a_reg[21]}]
set_load -pin_load 10 [get_ports {a_reg[20]}]
set_load -pin_load 10 [get_ports {a_reg[19]}]
set_load -pin_load 10 [get_ports {a_reg[18]}]
set_load -pin_load 10 [get_ports {a_reg[17]}]
set_load -pin_load 10 [get_ports {a_reg[16]}]
set_load -pin_load 10 [get_ports {a_reg[15]}]
set_load -pin_load 10 [get_ports {a_reg[14]}]
set_load -pin_load 10 [get_ports {a_reg[13]}]
set_load -pin_load 10 [get_ports {a_reg[12]}]
set_load -pin_load 10 [get_ports {a_reg[11]}]
set_load -pin_load 10 [get_ports {a_reg[10]}]
set_load -pin_load 10 [get_ports {a_reg[9]}]
set_load -pin_load 10 [get_ports {a_reg[8]}]
set_load -pin_load 10 [get_ports {a_reg[7]}]
set_load -pin_load 10 [get_ports {a_reg[6]}]
set_load -pin_load 10 [get_ports {a_reg[5]}]
set_load -pin_load 10 [get_ports {a_reg[4]}]
set_load -pin_load 10 [get_ports {a_reg[3]}]
set_load -pin_load 10 [get_ports {a_reg[2]}]
set_load -pin_load 10 [get_ports {a_reg[1]}]
set_load -pin_load 10 [get_ports {a_reg[0]}]
set_load -pin_load 10 [get_ports {b_reg[31]}]
set_load -pin_load 10 [get_ports {b_reg[30]}]
set_load -pin_load 10 [get_ports {b_reg[29]}]
set_load -pin_load 10 [get_ports {b_reg[28]}]
set_load -pin_load 10 [get_ports {b_reg[27]}]
set_load -pin_load 10 [get_ports {b_reg[26]}]
set_load -pin_load 10 [get_ports {b_reg[25]}]
set_load -pin_load 10 [get_ports {b_reg[24]}]
set_load -pin_load 10 [get_ports {b_reg[23]}]
set_load -pin_load 10 [get_ports {b_reg[22]}]
set_load -pin_load 10 [get_ports {b_reg[21]}]
set_load -pin_load 10 [get_ports {b_reg[20]}]
set_load -pin_load 10 [get_ports {b_reg[19]}]
set_load -pin_load 10 [get_ports {b_reg[18]}]
set_load -pin_load 10 [get_ports {b_reg[17]}]
set_load -pin_load 10 [get_ports {b_reg[16]}]
set_load -pin_load 10 [get_ports {b_reg[15]}]
set_load -pin_load 10 [get_ports {b_reg[14]}]
set_load -pin_load 10 [get_ports {b_reg[13]}]
set_load -pin_load 10 [get_ports {b_reg[12]}]
set_load -pin_load 10 [get_ports {b_reg[11]}]
set_load -pin_load 10 [get_ports {b_reg[10]}]
set_load -pin_load 10 [get_ports {b_reg[9]}]
set_load -pin_load 10 [get_ports {b_reg[8]}]
set_load -pin_load 10 [get_ports {b_reg[7]}]
set_load -pin_load 10 [get_ports {b_reg[6]}]
set_load -pin_load 10 [get_ports {b_reg[5]}]
set_load -pin_load 10 [get_ports {b_reg[4]}]
set_load -pin_load 10 [get_ports {b_reg[3]}]
set_load -pin_load 10 [get_ports {b_reg[2]}]
set_load -pin_load 10 [get_ports {b_reg[1]}]
set_load -pin_load 10 [get_ports {b_reg[0]}]
create_clock [get_ports clk]  -period 25  -waveform {0 12.5}
set_input_delay -clock clk  -max 0.2  [get_ports rst]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[31]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[30]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[29]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[28]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[27]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[26]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[25]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[24]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[23]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[22]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[21]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[20]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[19]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[18]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[17]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[16]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[15]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[14]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[13]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[12]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[11]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[10]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[9]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[8]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[7]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[6]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[5]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[4]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[3]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[2]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[1]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a_reg[0]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[31]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[30]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[29]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[28]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[27]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[26]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[25]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[24]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[23]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[22]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[21]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[20]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[19]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[18]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[17]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[16]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[15]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[14]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[13]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[12]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[11]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[10]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[9]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[8]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[7]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[6]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[5]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[4]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[3]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[2]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[1]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b_reg[0]}]
set_output_delay -max 0.5  [get_ports {result_reg[31]}]
set_output_delay -max 0.5  [get_ports {result_reg[30]}]
set_output_delay -max 0.5  [get_ports {result_reg[29]}]
set_output_delay -max 0.5  [get_ports {result_reg[28]}]
set_output_delay -max 0.5  [get_ports {result_reg[27]}]
set_output_delay -max 0.5  [get_ports {result_reg[26]}]
set_output_delay -max 0.5  [get_ports {result_reg[25]}]
set_output_delay -max 0.5  [get_ports {result_reg[24]}]
set_output_delay -max 0.5  [get_ports {result_reg[23]}]
set_output_delay -max 0.5  [get_ports {result_reg[22]}]
set_output_delay -max 0.5  [get_ports {result_reg[21]}]
set_output_delay -max 0.5  [get_ports {result_reg[20]}]
set_output_delay -max 0.5  [get_ports {result_reg[19]}]
set_output_delay -max 0.5  [get_ports {result_reg[18]}]
set_output_delay -max 0.5  [get_ports {result_reg[17]}]
set_output_delay -max 0.5  [get_ports {result_reg[16]}]
set_output_delay -max 0.5  [get_ports {result_reg[15]}]
set_output_delay -max 0.5  [get_ports {result_reg[14]}]
set_output_delay -max 0.5  [get_ports {result_reg[13]}]
set_output_delay -max 0.5  [get_ports {result_reg[12]}]
set_output_delay -max 0.5  [get_ports {result_reg[11]}]
set_output_delay -max 0.5  [get_ports {result_reg[10]}]
set_output_delay -max 0.5  [get_ports {result_reg[9]}]
set_output_delay -max 0.5  [get_ports {result_reg[8]}]
set_output_delay -max 0.5  [get_ports {result_reg[7]}]
set_output_delay -max 0.5  [get_ports {result_reg[6]}]
set_output_delay -max 0.5  [get_ports {result_reg[5]}]
set_output_delay -max 0.5  [get_ports {result_reg[4]}]
set_output_delay -max 0.5  [get_ports {result_reg[3]}]
set_output_delay -max 0.5  [get_ports {result_reg[2]}]
set_output_delay -max 0.5  [get_ports {result_reg[1]}]
set_output_delay -max 0.5  [get_ports {result_reg[0]}]
set_output_delay -max 0.5  [get_ports INF_reg]
set_output_delay -max 0.5  [get_ports NEG_INF_reg]
set_output_delay -max 0.5  [get_ports NAN_reg]
set_output_delay -max 0.5  [get_ports ERR_reg]
